my-default-targets: appcenter-versions

appcenter-versions:
	@echo "/ ########### #"
	@echo "* appcenter   : $(shell appcenter --version)"
	@echo "* nodejs      : $(shell node --version)"
	@echo "* npm         : $(shell npm --version)"
	@echo "\ ########### #"

appcenter-install:
	npm install -g appcenter-cli	
