my-default-targets: hello \
                    goodbye

hello-with-echo: 
	echo "Hello, to the world of make (should be seen twice)"

hello: 
	@echo "Hello, to the world of make (should be seen once)"
	
.PHONY: goodbye
goodbye: 
	@echo "Bye bye, see you next time!"
	
